# This rule is not used by the project dummy-site-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dummy-site.dummy-site.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dummy-site-crd
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-admin-role
rules:
- apiGroups:
  - dummy-site.dummy-site
  resources:
  - dummysites
  verbs:
  - '*'
- apiGroups:
  - dummy-site.dummy-site
  resources:
  - dummysites/status
  verbs:
  - get
