---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dummy-site.dummy-site
  resources:
  - dummysites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dummy-site.dummy-site
  resources:
  - dummysites/finalizers
  verbs:
  - update
- apiGroups:
  - dummy-site.dummy-site
  resources:
  - dummysites/status
  verbs:
  - get
  - patch
  - update
