apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-app
  namespace: wiki
  labels:
    app: wikipedia-app
spec:
  initContainers:
    - name: init-container
      image: curlimages/curl:latest
      command:
        [
          "curl",
          "-o",
          "/usr/share/nginx/html/index.html",
          "https://en.wikipedia.org/wiki/Kubernetes",
        ]
      volumeMounts:
        - name: wikipedia-content
          mountPath: /usr/share/nginx/html

  containers:
    - name: main-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: wikipedia-content
          mountPath: /usr/share/nginx/html

    - name: sidecar-container
      image: curlimages/curl:latest
      command:
        [
          "sh",
          "-c",
          "while true; do sleep $((RANDOM % 11 + 5))m && curl -o /usr/share/nginx/html/index.html https://en.wikipedia.org/wiki/Special:Random; done",
        ]
      volumeMounts:
        - name: wikipedia-content
          mountPath: /usr/share/nginx/html

  volumes:
    - name: wikipedia-content
      emptyDir: {}
