apiVersion: v1
kind: Service
metadata:
  name: wikipedia-app-service
  namespace: wiki
spec:
  type: LoadBalancer
  selector:
    app: wikipedia-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
