apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/cronjob.yaml

images:
  - name: crud/backend
    newname: toukop/crud-backend:latest
  - name: crud/backend-worker
    newname: toukop/crud-backend-worker:latest
