apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/cronjob.yaml

images:
  - name: crud/backend
    newname: europe-north1-docker.pkg.dev/nomadic-charge-446815-j2/kubernetes-course/crud-backend:latest
  - name: crud/backend-worker
    newname: europe-north1-docker.pkg.dev/nomadic-charge-446815-j2/kubernetes-course/crud-backend-worker:lastest
