apiVersion: v1
kind: Secret
metadata:
    name: pong-postgres-secrets
    namespace: log-pong
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IjKS6j+UeNDMvCoK4xP3VLJqQNY=,iv:g6iFR4F3egArTm2WHGUQpJj2aFAKOgYMOnI0vEgIKYo=,tag:E20JeqQ5o+dMpzytfjKl2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eu58fp6eyh9m0x0nnumlsyygylfh72tpk9r9w6lrftq2pqugyquq4tjdgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYjZGMUZlWFdHY2NIdzJF
            TXRtM1hNSlpKNnVLbEtlRWpiNmpGb0ZCM0dZCkR0aWd1QzZkOXczU3Z3SkNkalkv
            bmFpUGRZQ0I4QnRSUTQ1NFNucXZWSVUKLS0tIGVRVHhwZG8wSWVJZ3l1Sm1ZK09C
            SHgxUDhKYWF5ampEVlNSMlJ2WFYzaFUKWug8uw9IFGXydxkKzDW9u9Crv2GAPnGt
            4wtkC/d6uAoq96ufugNnvfPEmLwv7KR2F1TLz8RROb+o8inRA34hRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T09:43:48Z"
    mac: ENC[AES256_GCM,data:XGIkLAaAAmA0LZkkN4GPdYn4TStGZavmMsC65qIh84DshS3UQ+ZwO3KgTj81BixhOEI2i6oJZlD3dJEftoHZIi3KKPKm9FiZmJoVsSdiPeK+/0/bLsAqumqeXjKpL/33zssu5JbZYu+AaJAVbrJPIYcm8IgxAuYTlJ+QfdehFxM=,iv:cypim6lUA+EaQcrrIMls75Y7JlVWCr5MF+g4bI7FUWQ=,tag:OU4oxoXj6NXaPlxJ2t5fkg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.2
