apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml

images:
  - name: crud/app
    newname: europe-north1-docker.pkg.dev/nomadic-charge-446815-j2/kubernetes-course/crud-app:latest
