apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-postgres
  namespace: log-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-postgres
  template:
    metadata:
      labels:
        app: pong-postgres
    spec:
      containers:
        - name: pong-postgres
          image: "postgres:14"
