apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pong-pv
  namespace: log-pong
spec:
  storageClassName: log-pong-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crud-pv
  namespace: crud
spec:
  storageClassName: crud-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
