apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pong-postgres-stset
  namespace: log-pong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pong-postgres
  template:
    metadata:
      labels:
        app: pong-postgres
    spec:
      containers:
        - name: pong-postgres
          image: "postgres:14"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: pong-postgres-data-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pong-postgres-secrets
                  key: POSTGRES_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: pong-postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-postgres-stset
  namespace: crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-postgres
  template:
    metadata:
      labels:
        app: crud-postgres
    spec:
      containers:
        - name: crud-postgres
          image: "postgres:14"
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: crud-postgres-data-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crud-postgres-secrets
                  key: POSTGRES_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: crud-postgres-data-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
