apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: log-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes:
        - name: log-pong-volume
          persistentVolumeClaim:
            claimName: log-pong-claim
      containers:
        - name: pong
          image: toukop/pong:latest
          volumeMounts:
            - name: log-pong-volume
              mountPath: /usr/src/app/files
          env:
            - name: FILE_DIR
              value: /usr/src/app/files
