apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
  namespace: log-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes:
        - name: log-pong-volume
          persistentVolumeClaim:
            claimName: log-pong-claim
      containers:
        - name: pong
          image: europe-north1-docker.pkg.dev/nomadic-charge-446815-j2/kubernetes-course/pong:latest
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: log-pong-volume
              mountPath: /usr/src/app/files
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 1
            failureThreshold: 10
            successThreshold: 1
          env:
            - name: FILE_DIR
              value: /usr/src/app/files
            - name: PG_HOST
              value: pong-postgres-svc
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: postgres
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: pong-postgres-secrets
                  key: POSTGRES_PASSWORD
