apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: crud-backend
    spec:
      containers:
        - env:
            - name: NATS_URL
              value: nats://crud-nats:4222
            - name: PG_HOST
              value: crud-postgres-svc
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: postgres
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: crud-postgres-secrets
          image: crud/backend
          name: crud-backend
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
