apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      labels:
        app: crud-backend
    spec:
      containers:
        - name: crud-backend
          image: crud/backend
          resources:
            limits:
              cpu: "150m"
              memory: "512Mi"
          env:
            - name: PG_HOST
              value: crud-postgres-svc
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: postgres
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: crud-postgres-secrets
                  key: POSTGRES_PASSWORD
