apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: crud-app
    spec:
      containers:
        - env:
            - name: FILE_DIR
              value: /usr/src/app/files
          image: crud/app
          name: crud-app
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
          volumeMounts:
            - mountPath: /usr/src/app/files
              name: crud-volume
      volumes:
        - name: crud-volume
          persistentVolumeClaim:
            claimName: crud-claim
