apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
  namespace: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      volumes:
        - name: crud-volume
          persistentVolumeClaim:
            claimName: crud-claim
      containers:
        - name: crud-app
          image: crud/app
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
          volumeMounts:
            - name: crud-volume
              mountPath: /usr/src/app/files
          env:
            - name: FILE_DIR
              value: /usr/src/app/files
