apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-app-ingress
  namespace: crud
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: crud-app-svc
                port:
                  number: 2347
          - path: /img
            pathType: Exact
            backend:
              service:
                name: crud-app-svc
                port:
                  number: 2347
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: crud-backend-svc
                port:
                  number: 2348
